name: CI On macos

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v2
        with:
          repository: golang/go
          path: go
      - name: Install golang env
        run: sh -c "curl -L https://git.io/vQhTU | bash"
      - name: Patch ulimit
        run: |
          sudo sh -c '[ "$(ulimit -H -n)" = "unlimited" ] || ulimit -S -n $(ulimit -H -n)'
          sudo sh -c '[ "$(ulimit -H -d)" = "unlimited" ] || ulimit -S -d $(ulimit -H -d)'
      - name: Build and test under sudo.
        run: sudo bash all.bash
        working-directory: go/src
      - name: Reset owner
        run: sudo chown -R `id -un`:staff .
        working-directory: go
      - name: Clean
        run: bash clean.bash
        working-directory: go/src
      - name: Clean obj files.
        run: | 
          find . -iname "obj" | xargs rm -rf
          du -h -d 1
        working-directory: go
      - name: Compress for distribution.
        run: ZIPFILE=go-darwin-amd64-`date "+%Y%m%d"`.zip; zip -r $ZIPFILE go;
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: go-darwin-amd64*.zip
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: go-darwin-amd64*.zip
          tag: ${{ github.ref }}
          file_glob: true
